### ISSUE TITLE
This extension causing random crashes?

### ISSUE THREAD

**Issue by notNSANE** [kurtextrem/Layoutify-for-Instagram#103]
It's either this one or Ublock Origin and I doubt the latter is.

How can I help to debug this?

I suspect the "watch" feature is causing major issues, but it's just a guess. Might be nice to have the option to fully disable that, in any case?

**Comment by kurtextrem** [comment]
I'm pretty sure it is a Chrome bug (they're testing extension isolation). For me two extensions crashed in the latest Chrome Dev build, uBlock Origin and some other unrelated to Layoutify. After updating Chrome the issue was resolved.

**Comment by notNSANE** [comment]
It was a vendor issue after all! Closing
