### ISSUE TITLE
No way to download video on individual posts with video/video posts

### ISSUE THREAD

**Issue by notNSANE** [kurtextrem/Layoutify-for-Instagram#108]
Can you check this? The urls are 

* instagram.com/p/?????
* instagram.com/tv/?????

Where ????? is the unique ID assigned for the posts. You can access these entering any profile then any of these that has a video:  

![image](https://user-images.githubusercontent.com/7162375/140394976-fdab71f8-37f0-4c58-a341-a08d1518da84.png)

**Comment by kurtextrem** [comment]
Seen it too, Instagram changed something. I can only fix `/p/` and `/tv/` but not in modals I think
