### ISSUE TITLE
Like page not working

### ISSUE THREAD

**Issue by createvi** [kurtextrem/Layoutify-for-Instagram#112]
i just downloaded Layoutify and when i go likes section it shows like this 
![image](https://user-images.githubusercontent.com/93326280/173353449-8c0aa84a-73cc-4abc-9852-3485866e78c2.png)
And a very weird scaling on the home page of instagram.com while using this addon.

**Comment by createvi** [comment]
ahh i see, i there a way to use a previous verison on instsagram web :rofl:

**Comment by kurtextrem** [comment]
Sadly no :/

**Comment by createvi** [comment]
Fine, i guess i will wait for the fix
