### ISSUE TITLE
Instagram does NOT load with extension active as of Aug 22

### ISSUE THREAD

**Issue by fitzgedf** [kurtextrem/Layoutify-for-Instagram#120]
Starting today, Aug 22, Instagram does not load the page with this extension active.  Guessing some sort of "improvement" from their end which it never is.  Appreciate if you could look at the issue and see if it can be quickly fixed?

Thanks - Dan

**Comment by fitzgedf** [comment]
looks to be working again - Thanks if you did something and thanks for a great extension!

**Comment by kurtextrem** [comment]
Love it when it resolves on its own haha
