### ISSUE TITLE
Italian Translate

### ISSUE THREAD

**Issue by PaoloC95** [kurtextrem/Layoutify-for-Instagram#87]
Row 39 of english lang can be translated in italian as: Usa tema di sistema

**Comment by kurtextrem** [comment]
Thank you!
How would you translate "The Night Mode gets activated when the System is also in night mode."?

**Comment by PaoloC95** [comment]
Is translate as: "La Dark Mode viene attivata quando il sistema passa in Dark Mode"
"Tema Notturno" can be translated as "Dark Mode"
Abilita Tema Notturno -> Abilita Dark Mode
Ora di Inizio del Tema Notturno -> Ora di Inizio della Dark Mode
Ora di Fine del Tema Notturno -> Ora di Fine della Dark Mode

**Comment by kurtextrem** [comment]
Thank you, will be live with the next update!

**Comment by PaoloC95** [comment]
This buttons can be translated also there.
screen below.

Like -> Mi Piace
Collections -> Elementi Salvati
Options -> Opzioni
About -> Riguardo a

![Immagine](https://user-images.githubusercontent.com/43925971/103649381-a1806b00-4f5e-11eb-8f5a-8cfd19a25691.png)
