### ISSUE TITLE
with the insta's  new update that shows explore page also, the video controls you have designed no longer work, i really like this extension, please find a way to apply video controls for the vios in the explore page

### ISSUE THREAD

**Issue by yugal-kishore143** [kurtextrem/Layoutify-for-Instagram#92]

**Comment by kurtextrem** [comment]
Do you mean when you click on a video on the explore page?

**Comment by yugal-kishore143** [comment]
yes yes, the video controls on explore page of the website doesn't work
anymore, even in home page it doesn't control, only if I open the video in
anew page sometimes it's working, this is happening since the website got a
new update

**Comment by yugal-kishore143** [comment]
it's working fine now, I guess I had to update my chrome
thank you
