### ISSUE TITLE
Pressing "load more" loads the same set of likes that were already visible

### ISSUE THREAD

**Issue by ibrahimt13** [kurtextrem/Layoutify-for-Instagram#95]
Not sure if it's something wrong on my end or with the extension itself

**Comment by kurtextrem** [comment]
It's neither, Instagram changed something and I (up to now) could not find out what exactly. I checked the code and functionality multiple times, nothing has been changed on my side.

Technically this is what's happening: I tell Instagram to load the first page, the first page says there is a page 2. Then I tell Instagram to load "page 2" and it returns the first page again.

**Comment by kurtextrem** [comment]
Fixed in v3.3.3.6. They removed a space :)
