### ISSUE TITLE
Single post page image dimensions are smaller

### ISSUE THREAD

**Issue by akilan27** [kurtextrem/Layoutify-for-Instagram#96]
The image size on stand-alone post page (not single post modal on main page) is smaller with the extension enabled compared to the page without this extension. Thanks for looking into this.

**Comment by kurtextrem** [comment]
Hi Akilan, may I ask what your screen resolution and screen height & width is? I think there might be the issue (which I'll fix once I find it), because on my monitor (1080p) the images are bigger compared to when I turn the extension off.

**Comment by akilan27** [comment]
Hi,
That was fast. :-) Screen resolution is 1440x900 (Macbook Air, running Ubuntu, Google Chrome). Viewport height is 765. Note that the display of the image + sidebar with comments is what becomes smaller. The image itself is of high resolution and looks fine when opened in new tab.

**Comment by kurtextrem** [comment]
I'm right now thinking of how to fix this best. Thank you for your patience.

**Comment by akilan27** [comment]
Thank you!

**Comment by kurtextrem** [comment]
You're welcome :)
